
spring:
  ## 文件上传限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



info:
  version: @project.version@

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'




