server:
  port: 7201
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672    # RabbitMQ的监听端口
    username: zhzy  # 用户名
    password: zhzy123 # 密码

management:
  endpoints:
    web:
      exposure:
        include: "*"